# Generated by Django 4.1.4 on 2022-12-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_options_user_deleted_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='deleted_at',
        ),
    ]
